version: '3.8'

services:
  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_API_URL=http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./app:/app
      - /app/node_modules

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/elections
      - PORT=4000
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: